### ISSUE TITLE
Make available functionality more clear

### ISSUE THREAD

**Issue by juliuscc** [juliuscc/speak.exchange#131]
We got this feedback:

> It might be good if there is some text on the start page explaining what kind of application this is and what type of input that is expected.

This can probably be solved by providing a better message on the first page.

**Comment by blendaf** [comment]
like for example: welcome to speak repeat, input a word to get the translation.

**Comment by Falcasantos** [comment]
Should speak.repeat have something in a sort of modal pop-up introduction? Or something static like on speak.exchange?

**Comment by juliuscc** [comment]
If a user doesn't have any decks, and is logged in, I think there should be a nice message on `/repeat`

**Comment by juliuscc** [comment]
A bit like if they haven't inputted anything on `/`
