### ISSUE TITLE
Consistent error messages

### ISSUE THREAD

**Issue by juliuscc** [juliuscc/speak.exchange#134]
We should have consistent error handling. Here is an expample of inconsistent error handling:

![bild](https://user-images.githubusercontent.com/8337202/78816194-a9ac7980-79d1-11ea-8732-0a149bf3c143.png)

I think the best solution to this is to add an 'info box' that is a yellow, less aggressive version of the error box. We can use that for information that is not an error.

**Comment by blendaf** [comment]
Not sure how difficult this one is to do, but let me know if it is too much
