### ISSUE TITLE
Refreshing on view deck crashes

### ISSUE THREAD

**Issue by juliuscc** [juliuscc/speak.exchange#139]
Go to https://speak.exchange/view-deck?id=pZa3RZC5S1HSXbJ2o7Vi to reproduce.

**Comment by blendaf** [comment]
Do not get this error on the localhost. The problem also exists when refreshing on edit deck. Can be recreated locally by running. npm run ci-build and npx serve out

**Comment by blendaf** [comment]
This is because `router.query` is undefined on the first render: https://github.com/zeit/next.js/discussions/11484

**Comment by blendaf** [comment]
fixed by structure update
