### ISSUE TITLE
Search results being incorrectly modified

### ISSUE THREAD

**Issue by Falcasantos** [juliuscc/speak.exchange#159]
Might have to do with the unicode arrow removal? The result should be "dire bonjour (**à** [qqn])"
![image](https://user-images.githubusercontent.com/27318638/79117204-cad2e880-7d8a-11ea-8f41-671c2098f6c7.png)
![image](https://user-images.githubusercontent.com/27318638/79117219-d0303300-7d8a-11ea-8b50-278798dac4c4.png)

**Comment by blendaf** [comment]
Yes that could definitely be it
