### ISSUE TITLE
Project submission

### ISSUE THREAD

**Issue by blendaf** [juliuscc/speak.exchange#194]
- [ ] 1. Name of the group participants and personnumer
- [ ] 2. Link to your GitHub repository
- [ ] 3. README file explaining how to setup
- [ ] 4. Link to running version of the web app (see bellow)
- [ ] 5. Text files (gladly with pictures) on documented user feedback and how it was acted upon

**Note: add your names + personnummer or eqv in the comment below**

**Comment by blendaf** [comment]
Blenda Fröjdh 970706-0787

**Comment by juliuscc** [comment]
Julius Celik 971024-5474

**Comment by blendaf** [comment]
1. Group Members
Blenda Fröjdh 970706-0787
Julius Celik 971024-5474
Robert Falcasantos 980316-2875
Catarina Allen 
2. https://github.com/juliuscc/speak.exchange.git
3. See the README for the github repo
4. https://speak.exchange/
5. Please see the folder [speak.exchange/evaluations](https://github.com/juliuscc/speak.exchange/tree/master/evaluations)

**Comment by juliuscc** [comment]
Shouldn't we merge the user-evaluation branch?

**Comment by blendaf** [comment]
I would assume, but just wrote that for now just in case

**Comment by Falcasantos** [comment]
Updated with my personnummer and link to the folder on master
