### ISSUE TITLE
Improve styling of language select

### ISSUE THREAD

**Issue by blendaf** [juliuscc/speak.exchange#21]
@blendaf

**Comment by juliuscc** [comment]
Maybe this will be removed or changed.

**Comment by Falcasantos** [comment]
If we're hardcoding it to just EN/FR then we can just change it to show English > French and have an arrow button that can be clicked on to switch to French > English, perhaps?

**Comment by juliuscc** [comment]
Yes, good point! Why did we decide on doing only EN/FR btw? I can't remember? Was it only because it was difficult to style the input?

**Comment by blendaf** [comment]
Functionality working and styling is acceptable
