### ISSUE TITLE
Add routing for search queries

### ISSUE THREAD

**Issue by Falcasantos** [juliuscc/speak.exchange#26]
First page routes to speak.exchange/ but the minute you start typing, routes to speak.exchange/search/, to which the search input debounces to the URL bar, from which a hook checks before updating the search.

- speak.exchange/search/nation
- speak.exchange/search/pluie
- speak.exchange/search/référence

**Comment by juliuscc** [comment]
There is some complexity involved in having the same view for both ’/’ and ’/search’. I suggest that we start by using query parameters as an mvp, and later change them to other parameters.

**Comment by juliuscc** [comment]
Note: check nextjs dynamic routes for other parameters.
