### ISSUE TITLE
Bug: default search state is "undefined", literally

### ISSUE THREAD

**Issue by Falcasantos** [juliuscc/speak.exchange#36]
When URL = localhost:3000 || speak.exchange, then you get [this](https://imgur.com/BqcJsi2).

**Comment by juliuscc** [comment]
Let's have a check to see if `search` is '', and set the translation to null or undefined then.

**Comment by juliuscc** [comment]
Here: https://github.com/juliuscc/speak.exchange/blob/57bc9a6bcf4ab38b25551d32712b2ffe0684d87a/container/Exchange.js#L34-L43

We can do this:

```javascript
useEffect(() => {
  if (search === '')
    return setTranslation(null)

   let cancelled = false 
  
   setLoading(true) 
  
   fetchTranslation(search, 'en', 'fr').then(response => { 
     if (cancelled) return 
     setLoading(false) 
     setTranslation(response) 
   }) 
```

**Comment by juliuscc** [comment]
Also, it makes more sense to use `null` instead of `undefined` as the state for _'no translations exists'_.
