### ISSUE TITLE
Index as key in Translation map disrupts alternating background colouring

### ISSUE THREAD

**Issue by Falcasantos** [juliuscc/speak.exchange#46]
Index gives us this—the double zero leads to a disruption in the alternation:
![image](https://user-images.githubusercontent.com/27318638/75887047-7ce0d180-5e29-11ea-923c-d7792b54b48a.png)
And it looks like this:
![image](https://user-images.githubusercontent.com/27318638/75887104-908c3800-5e29-11ea-897a-8692a058f257.png)

**Comment by juliuscc** [comment]
This is fixed
