### ISSUE TITLE
Search can't take in words with accents

### ISSUE THREAD

**Issue by Falcasantos** [juliuscc/speak.exchange#47]
This will pose an issue when translating from fr->en. I tried by switching the call in `Exchange.js` to `'fr', 'en'` and it comes up with the same error.

![image](https://user-images.githubusercontent.com/27318638/75887866-bcf48400-5e2a-11ea-99f5-afd200fbb278.png)

**Comment by juliuscc** [comment]
We might have to url-encode the terms before sending them to the api. I can look into it

**Comment by juliuscc** [comment]
Fixed by changing so that the cloud function uses https instead of http
