### ISSUE TITLE
Letter selector CSS needs restyling, sets 'undefined' when clicking with empty search query on master

### ISSUE THREAD

**Issue by Falcasantos** [juliuscc/speak.exchange#64]
<img width="960" alt="Capture d’écran 2020-03-11 à 12 35 03" src="https://user-images.githubusercontent.com/27318638/76413021-f5e5a900-6394-11ea-893b-1f313e70ce44.png">

(I have a feeling though that #62 by @juliuscc fixes the undefined bug by declaring `search = ''`)

**Comment by juliuscc** [comment]
#62 fixed the `undefined` bug but not styling. #65 mitigates a bit of the styling bug, but the styling has to be changed more.
