### ISSUE TITLE
Apostrophe in search on mobile causes error on s.e

### ISSUE THREAD

**Issue by Falcasantos** [juliuscc/speak.exchange#87]
![IMG_8518](https://user-images.githubusercontent.com/27318638/77942061-66f4ee00-72bb-11ea-8e32-1334b2237649.PNG)
![IMG_8519](https://user-images.githubusercontent.com/27318638/77942072-69efde80-72bb-11ea-89ed-49535c944433.PNG)

**Comment by Falcasantos** [comment]
This works fine on desktop btw
<img width="1108" alt="Capture d’écran 2020-03-30 à 19 20 49" src="https://user-images.githubusercontent.com/27318638/77942216-973c8c80-72bb-11ea-8974-7a942bb54def.png">

**Comment by juliuscc** [comment]
Strange that it works on desktop

**Comment by juliuscc** [comment]
I get the same results. It works on desktop but not on mobile. We could try doing a url-encoding
